apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      containers:
        - name: devsecops-app
          image: your-docker-image:latest  # Replace with your actual image
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-service
spec:
  selector:
    app: devsecops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
